# Generated by Django 5.1.1 on 2025-07-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeevent',
            name='city',
            field=models.CharField(default='Chicago', max_length=100),
        ),
    ]
